Repository uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder, pull requests merged in 2024-04, with the labels that each got.

#281 Implemented UI/UX Design for Template Gallery page
  ui/client/src/components/LandingPage.css
  ui/client/src/components/NavBar.js
  ui/client/src/components/ProfilePage.js
  ui/client/src/components/templates.js
Labels: Templates Team

#285 user-to-personal-info-migration
  api/database/db.sql
  api/src/controllers/personal.info.controller.js
  api/src/controllers/users.controller.js
  api/src/routes/personal.info.routes.js
  api/src/routes/users.routes.js
Labels: enhancement

#284 added basic input error handling for additional info sections
  ui/client/src/components/ResumeModals/additionalModal.js
Labels: enhancement

#283 created resume and sections linked tables
  api/database/db.sql
  api/package-lock.json
  api/package.json
Labels: enhancement

#287 Personal info edit page
  api/database/db.sql
  api/src/controllers/personal.info.controller.js
  api/src/routes/personal.info.routes.js
  ui/client/src/App.js
  ui/client/src/components/PersonalInfo/PersonalInfo.js
Labels: enhancement, Data Entry Team
